---
driver:
  name: dokken
  chef_version: latest
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken
  client_rb:
    environment: kitchen

verifier:
  name: inspec
  format: doc

platforms:
  - name: centos-7
    driver:
      image: centos:7.3.1611
      intermediate_instructions:
        - RUN yum clean all
        - RUN yum -y install net-tools lsof
      pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: server
    run_list:
      - recipe[custom_nfs::default]
      - role[nfs_server]
  - name: client
    run_list:
      - recipe[custom_nfs::default]
      - role[nfs_client]
