---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    environment: kitchen

verifier:
  name: inspec
  format: doc

platforms:
  - name: centos-7.2
    driver:
      box: packer_centos7_virtualbox
      box_url: ~/packer_vbox_builds/packer_centos7_virtualbox.box

suites:
  - name: server
    run_list:
      - recipe[custom_nfs::default]
      - role[nfs_server]
    attributes:
    driver_config:
      vagrantfiles:
        - vagrant_disk.rb
      network:
        - ['private_network', {ip: '33.33.33.2'}]
  - name: server
    run_list:
      - recipe[custom_nfs::default]
      - role[nfs_client]
    driver_config:
      network:
        - ['private_network', {ip: '33.33.33.3'}]
    attributes:
