AllCops:
  Exclude:
    - '.kitchen/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
Metrics/LineLength:
  Enabled: false
Style/HashSyntax:
  Enabled: false
ParenthesesAsGroupedExpression:
  Enabled: false
