name 'custom_nfs'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures custom_nfs'
long_description 'Installs/Configures custom_nfs'
version '0.1.0'

depends 'firewalld', '~> 1.1.0'
depends 'lvm', '~> 3.0.0'
depends 'nfs', '~> 2.2.0'
