default['custom_nfs']['nfs_share'] = '/data'
default['custom_nfs']['share_to'] = '192.168.0.1/24'
default['custom_nfs']['mount_from'] = '192.168.0.2'
default['custom_nfs']['writable'] = 'true'
default['custom_nfs']['sync'] = 'true'
default['custom_nfs']['share_options'] = 'data'
default['custom_nfs']['mount_options'] = 'default,noatime,nodiratime,vers=3'
